package com.github.donghune.dimgame.minigame.fast_combination

import org.bukkit.Material

object Combination {
    val items = listOf(
        Material.CRAFTING_TABLE to "조합대",
        Material.STICK to "막대기",
        Material.WOODEN_AXE to "나무 도끼",
        Material.WOODEN_HOE to "나무 괭이",
        Material.WOODEN_PICKAXE to "나무 곡괭이",
        Material.WOODEN_SHOVEL to "나무 삽",
        Material.WOODEN_SWORD to "나무 검",
        Material.STONE_AXE to "돌 도끼",
        Material.STONE_HOE to "돌 괭이",
        Material.STONE_PICKAXE to "돌 곡괭이",
        Material.STONE_SHOVEL to "돌 삽",
        Material.STONE_SWORD to "돌 검",
        Material.IRON_AXE to "철 도끼",
        Material.IRON_HOE to "철 괭이",
        Material.IRON_PICKAXE to "철 곡괭이",
        Material.IRON_SHOVEL to "철 삽",
        Material.IRON_SWORD to "철 검",
        Material.GOLDEN_AXE to "금 도끼",
        Material.GOLDEN_HOE to "금 괭이",
        Material.GOLDEN_PICKAXE to "금 곡괭이",
        Material.GOLDEN_SHOVEL to "금 삽",
        Material.GOLDEN_SWORD to "금 검",
        Material.DIAMOND_AXE to "다이아몬드 도끼",
        Material.DIAMOND_HOE to "다이아몬드 괭이",
        Material.DIAMOND_PICKAXE to "다이아몬드 곡괭이",
        Material.DIAMOND_SHOVEL to "다이아몬드 삽",
        Material.DIAMOND_SWORD to "다이아몬드 검",
        Material.STONE_BRICKS to "돌 벽돌",
        Material.CHEST to "상자",
        Material.NOTE_BLOCK to "노트 블럭",
        Material.CAKE to "케이크",
        Material.WHITE_BED to "하얀 침대",
        Material.SHIELD to "방패",
        Material.JACK_O_LANTERN to "잭 오 랜턴",
        Material.SHEARS to "가위",
        Material.RED_STAINED_GLASS_PANE to "빨간 색유리 판",
        Material.YELLOW_STAINED_GLASS_PANE to "노란 색유리 판",
        Material.IRON_DOOR to "철 문",
        Material.DARK_OAK_DOOR to "짙은 참나무 문",
        Material.OAK_PRESSURE_PLATE to "참나무 갑압판",
        Material.COOKIE to "쿠키",
        Material.GOLDEN_CARROT to "황금 당근",
        Material.RED_WOOL to "빨간 양털",
        Material.LEATHER_BOOTS to "가죽 장화",
        Material.DIAMOND_HELMET to "다이아몬드 헬멧",
        Material.BLUE_DYE to "파랑 염료",
    )
}